graph LR
A --> B
C --- D
E -- add text --- F
G -- add text --> H
I --- |different syntax for add text|J
K --> |different syntax for add text| L
M -.-> N
O -.- P
Q -. text .-> R
S -. text .- T
U ==> V
W === X
Y == text === Z
AA == text ==> AB